//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleRulesExtensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleRulesExtensions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имена классов должны начинаться с большой буквы.
        /// </summary>
        internal static string ClassNaminAnalyzerDescription {
            get {
                return ResourceManager.GetString("ClassNaminAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класс {0} должен начинаться с большой буквы.
        /// </summary>
        internal static string ClassNaminAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("ClassNaminAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имена классов должны начинаться с большой буквы.
        /// </summary>
        internal static string ClassNaminAnalyzerTitle {
            get {
                return ResourceManager.GetString("ClassNaminAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название константы должно быть в CapitalCase.
        /// </summary>
        internal static string ConstantCapitalCaseDescription {
            get {
                return ResourceManager.GetString("ConstantCapitalCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Константа {0} назване неправильно.
        /// </summary>
        internal static string ConstantCapitalCaseMessageFormat {
            get {
                return ResourceManager.GetString("ConstantCapitalCaseMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Константы именуем CapitalCase.
        /// </summary>
        internal static string ConstantCapitalCaseTitle {
            get {
                return ResourceManager.GetString("ConstantCapitalCaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локальные переменные должны быть в camelCase.
        /// </summary>
        internal static string LocalVariableCamelCaseDescription {
            get {
                return ResourceManager.GetString("LocalVariableCamelCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переменная {0} должна быть в camelCase.
        /// </summary>
        internal static string LocalVariableCamelCaseMessageFormat {
            get {
                return ResourceManager.GetString("LocalVariableCamelCaseMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локальные переменные должны быть в camelCase.
        /// </summary>
        internal static string LocalVariableCamelCaseTitle {
            get {
                return ResourceManager.GetString("LocalVariableCamelCaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы помечаем все асинхронные функции словом Async в конце. Исключения: публичные методы контроллеров.
        /// </summary>
        internal static string MethodEndsAsyncAnalyzerDescription {
            get {
                return ResourceManager.GetString("MethodEndsAsyncAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавьте Async в конец имени {0}.
        /// </summary>
        internal static string MethodEndsAsyncAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MethodEndsAsyncAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использование асинхроннной функции без Async в конце имени.
        /// </summary>
        internal static string MethodEndsAsyncAnalyzerTitle {
            get {
                return ResourceManager.GetString("MethodEndsAsyncAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имена методов должны начинаться с большой буквы.
        /// </summary>
        internal static string MethodNaminAnalyzerDescription {
            get {
                return ResourceManager.GetString("MethodNaminAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод {0} должен начинаться с большой буквы.
        /// </summary>
        internal static string MethodNaminAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MethodNaminAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имена методов должны начинаться с большой буквы.
        /// </summary>
        internal static string MethodNaminAnalyzerTitle {
            get {
                return ResourceManager.GetString("MethodNaminAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приватные поля начинаются с _ в camelCase.
        /// </summary>
        internal static string PrivateFieldNamingDescription {
            get {
                return ResourceManager.GetString("PrivateFieldNamingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приватное поле {0} должно начинаться c _ в camelCase.
        /// </summary>
        internal static string PrivateFieldNamingMessageFormat {
            get {
                return ResourceManager.GetString("PrivateFieldNamingMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приватные поля начинаются с _ в camelCase.
        /// </summary>
        internal static string PrivateFieldNamingTitle {
            get {
                return ResourceManager.GetString("PrivateFieldNamingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имена свойств должны начинаться с большой буквы.
        /// </summary>
        internal static string PropertyNaminAnalyzerDescription {
            get {
                return ResourceManager.GetString("PropertyNaminAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойство {0} должен начинаться с большой буквы.
        /// </summary>
        internal static string PropertyNaminAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("PropertyNaminAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имена свойств должны начинаться с большой буквы.
        /// </summary>
        internal static string PropertyNaminAnalyzerTitle {
            get {
                return ResourceManager.GetString("PropertyNaminAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В именах допускается указывать только символы английского алфавита.
        /// </summary>
        internal static string RightNamingAnalyzerDescription {
            get {
                return ResourceManager.GetString("RightNamingAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В имени {0} присутствуют недопустимые сиволы, их нужно исправить.
        /// </summary>
        internal static string RightNamingAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("RightNamingAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В имени присутствуют недопустимые символы.
        /// </summary>
        internal static string RightNamingAnalyzerTitle {
            get {
                return ResourceManager.GetString("RightNamingAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Относительно предыдущей строки можно делать отступ в один таб или не делать совсем.
        /// </summary>
        internal static string SpaceChainDescription {
            get {
                return ResourceManager.GetString("SpaceChainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружена разница в отступе в {0}, при ожидаемом отступе {1}.
        /// </summary>
        internal static string SpaceChainMessageFormat {
            get {
                return ResourceManager.GetString("SpaceChainMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отступы между разными строками должны быть в пределах таба.
        /// </summary>
        internal static string SpaceChainTitle {
            get {
                return ResourceManager.GetString("SpaceChainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы не используем скобочки, если в теле if только один оператор..
        /// </summary>
        internal static string UnnecssaryIfBracesAnalyzerDescription {
            get {
                return ResourceManager.GetString("UnnecssaryIfBracesAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужно удалить скобочки в if.
        /// </summary>
        internal static string UnnecssaryIfBracesAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("UnnecssaryIfBracesAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использование не обязательных скобочек.
        /// </summary>
        internal static string UnnecssaryIfBracesAnalyzerTitle {
            get {
                return ResourceManager.GetString("UnnecssaryIfBracesAnalyzerTitle", resourceCulture);
            }
        }
    }
}
